name: Deploy

on:
  push:
    branches:
      - main

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify Backend Directory
        run: |
          ls -la
      - name: Pull Docker Image from Docker Hub
        run: |
          docker pull mspilot-backend:latest
      - name: Verify Pulled Docker Image
        run: |
          docker images
      - name: Deploy Backend to Server 
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_APP_NAME }}
          heroku_email: "yasser.abassi.ya@gmail.com"
          
