name: Deploy

on:
  push:
    branches:
      - main

jobs:
  pulling-image-from-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pull Docker Image from Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull mspilot-backend:latest
      - name: Verify Pulled Docker Image
        run: |
          docker images
      - name: Deploy Backend to Server 
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_APP_NAME }}
          heroku_email: "yasser.abassi.ya@gmail.com"
          
